---

- name: Check for Golang installation
  shell: runuser -l '{{ ansible_user }}' -c "command -v go 2>/dev/null"
  register: golang_install
  ignore_errors: yes

- name: Assert that Golang is installed
  assert:
    that:
      - golang_install.rc == 0
    fail_msg: "Golang installation not found, unable to proceed"
    success_msg: "Golang installation found"

- set_fact:
    golang_bin: "{{ golang_install.stdout }}"

- name: Assert that system user accounts have been specified
  assert:
    that:
      - docker_ecr_users is defined and docker_ecr_users|length > 0
    fail_msg: "No user accounts have been specified for this role"
    success_msg: "Found user accounts"

- name: Assert that Docker ECR environment config is present
  assert:
    that:
      - docker_ecr_environment is defined
    fail_msg: "No configuration found for this role"
    success_msg: "Found configuration"

- name: Install Docker ECR credential helper
  command:
    "{{ golang_bin }} get -u github.com/awslabs/amazon-ecr-credential-helper/ecr-login/cli/docker-credential-ecr-login"
  args:
    creates: /root/go/bin/docker-credential-ecr-login

- name: Install system-wide Docker ECR credential helper
  copy:
    src: /root/go/bin/docker-credential-ecr-login
    dest: "{{ ecr_credential_binary }}"
    owner: root
    group: root
    mode: '0755'
    remote_src: yes

- name: Configure user account(s) for Docker ECR authentication
  include_tasks: user.yml
  loop: "{{ docker_ecr_users }}"
  loop_control:
    loop_var: user
