---

- debug:
    msg: "Configuring Docker ECR authentication for user: {{ user }}"

- name: Create Docker configuration directory
  become_user: "{{ user }}"
  become: yes
  file:
    mode: 0755
    path: "/home/{{ user }}/.docker"
    state: directory

- name: Install Docker authentication configuration
  become_user: "{{ user }}"
  become: yes
  template:
    src: "{{ item }}.j2"
    dest: "/home/{{ user }}/.docker/{{ item }}"
    mode: 0755
  with_items:
    - config.json
